# Generated by Django 6.0.6 on 2026-07-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_customuser_description_customuser_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
